p8105\_hw3\_zc2443
================
Ziyang Chen
10-07-2019

## Question 1

``` r
library(p8105.datasets)
data("instacart")

str(instacart) #take a brief view of the dataset
```

The `instacart` dataset contains 15 variables and 1384617 observations.
There are 11 numeric variables and 4 character variables. The dataset
records data of rading information for some commodities. Some of the key
variables are product id, order number, reordered, days since prior
order and aisle\_id. For example, 4 product with id 49302 in aisle with
id 120 is purchased and has ever been repurchased. The last time that
this product got purchased was 9 days ago.

``` r
instacart %>% 
  group_by(aisle) %>% 
  summarize(n_obs = n()) %>% #find the number of ordered items for each aisle
  arrange(desc(n_obs)) 
```

There are 134 aisles. The most items are ordered from fresh vegetables
asile.

``` r
instacart %>% 
  group_by(aisle) %>% 
  summarize(n_obs = n()) %>% 
  filter(n_obs > 10000) %>% #filter to get aisles with 10000+ ordered items
  arrange(aisle) %>% #arrange by aisle names alphabetically
  ggplot(aes(x = aisle, y = n_obs)) + geom_bar(stat = "identity") + #use bar plot
  theme_classic() + #change the theme
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + #rotate the labels of x-axis to 45 degrees
  scale_y_continuous(breaks = seq(10000,160000,5000)) + #set the break points on y-axis
  labs(x = "Aisle names", y = "Number of items ordered") #name x-axis and y-axis
```

![](p8105_hw3_zc2443_files/figure-gfm/unnamed-chunk-3-1.png)<!-- --> The
number of items ordered for Fresh fruits and fresh vegetables aisles are
way more than other items.

``` r
instacart %>% 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>% 
  group_by(aisle, product_name) %>% 
  summarize(tot_order = sum(order_number)) %>% #sum up the times each item is ordered
  mutate(ord_ranking = min_rank(desc(tot_order))) %>% #assign each number of times each item is ordered a rank under grouping
  filter(ord_ranking %in% c(1,2,3)) %>% #select only the top 3 ranking
  arrange(aisle, ord_ranking) %>% 
  knitr::kable()
```

| aisle                      | product\_name                                 | tot\_order | ord\_ranking |
| :------------------------- | :-------------------------------------------- | ---------: | -----------: |
| baking ingredients         | Light Brown Sugar                             |       8605 |            1 |
| baking ingredients         | Cane Sugar                                    |       6244 |            2 |
| baking ingredients         | Organic Vanilla Extract                       |       6003 |            3 |
| dog food care              | Standard Size Pet Waste bags                  |        675 |            1 |
| dog food care              | Beef Stew Canned Dog Food                     |        631 |            2 |
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |        589 |            3 |
| packaged vegetables fruits | Organic Baby Spinach                          |     171301 |            1 |
| packaged vegetables fruits | Organic Raspberries                           |     113932 |            2 |
| packaged vegetables fruits | Organic Blueberries                           |      86765 |            3 |

The three most popular items of baking ingredients aisle are light brown
sugar with 8605 times of order, cane sugar with 6244 times of order, and
organic banilla extract with 6003 times of order; those of dog food care
are standard size pet waste bags with 675 times of order, beef stew
canned dog food with 631 times of order, and snack sticks chicken & rice
recipe dog treats with 589 times of order; those of packaged vegetables
fruits are organic baby spinach with 171301 times of order, organic
rasberries with 113932 times of order, and organic blue berries with
86765 times of order.

``` r
instacart %>% 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>% #filter the dataset
  group_by(product_name, order_dow) %>% 
  summarize(mean_order_hour_of_day = mean(order_hour_of_day)) %>% #find the mean of order hour of day under grouping
  pivot_wider(names_from = order_dow, values_from = mean_order_hour_of_day) %>% #untidy the dataset to generate a 2x7 table
  knitr::kable()
```

| product\_name    |        0 |        1 |        2 |        3 |        4 |        5 |        6 |
| :--------------- | -------: | -------: | -------: | -------: | -------: | -------: | -------: |
| Coffee Ice Cream | 13.77419 | 14.31579 | 15.38095 | 15.31818 | 15.21739 | 12.26316 | 13.83333 |
| Pink Lady Apples | 13.44118 | 11.36000 | 11.70213 | 14.25000 | 11.55172 | 12.78431 | 11.93750 |

We can see that the mean order hour of day is highest on Tuseday for
coffee ice cream and on Wednesday for pink lady apples.
